# Site settings
author: Rollin Metzger
title: Digital Expedition
header-img: img/home-bg.png
email: rollin.metzger@gmail.com
copyright_name: Rollin Metzger
description: > # this means to ignore newlines until "baseurl:"
  Wanderings
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  alcesalces11331

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
